/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenerator.models;

import jenerator.annnotations.FieldGenerable;
import jenerator.annnotations.Generable;

@Generable
public class Person {

	@FieldGenerable
	private String nombre;
	
	@FieldGenerable(unique = true)
	private int edad;

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEdad() {
		return edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}
}
